-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."submissions" add column "proof_of_account_ownership" text
--  not null;
